# Generated by Django 6.0.2 on 2026-02-21 02:55

import people.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('oscar_winner', models.BooleanField(blank=True, null=True, verbose_name='Academy Award Winner')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('nationality', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nationality')),
                ('agent_email', models.EmailField(max_length=254, unique=True, validators=[people.validator.agent_validate_email_domain])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('oscar_winner', models.BooleanField(blank=True, null=True, verbose_name='Academy Award Winner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('oscar_winner', models.BooleanField(blank=True, null=True, verbose_name='Academy Award Winner')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
