# Generated by Django 6.0.2 on 2026-02-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_actor_image_file_director_image_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='director',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
