# Generated by Django 6.0.2 on 2026-02-21 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_actor_slug_director_slug_writer_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='image_file',
            new_name='person_profile_image_file',
        ),
        migrations.RenameField(
            model_name='director',
            old_name='image_file',
            new_name='person_profile_image_file',
        ),
        migrations.RenameField(
            model_name='writer',
            old_name='image_file',
            new_name='person_profile_image_file',
        ),
    ]
