# Generated by Django 6.0.2 on 2026-02-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_rename_image_file_actor_person_profile_image_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='person_profile_image_file',
            field=models.ImageField(blank=True, null=True, upload_to='people/'),
        ),
        migrations.AlterField(
            model_name='director',
            name='person_profile_image_file',
            field=models.ImageField(blank=True, null=True, upload_to='people/'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='person_profile_image_file',
            field=models.ImageField(blank=True, null=True, upload_to='people/'),
        ),
    ]
