# Generated by Django 6.0.2 on 2026-02-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('founded_in', models.DateField(blank=True, null=True)),
                ('studio_head', models.CharField(blank=True, max_length=30, null=True)),
                ('in_production', models.ManyToManyField(blank=True, null=True, related_name='in_production', to='movies.movie')),
            ],
        ),
    ]
