# Generated by Django 6.0.2 on 2026-02-21 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studio',
            name='in_production',
        ),
    ]
