# Generated by Django 6.0.2 on 2026-02-21 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_movie_studio'),
        ('studios', '0002_remove_studio_in_production'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Studio',
        ),
    ]
