# Generated by Django 6.0.2 on 2026-02-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studios', '0003_delete_studio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('founded_in', models.DateField(blank=True, null=True)),
                ('studio_head', models.CharField(blank=True, max_length=30, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
