# Generated by Django 6.0.2 on 2026-02-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='studio_logo_file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
