# Generated by Django 6.0.2 on 2026-02-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0005_studio_studio_logo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='studio_logo_file',
            field=models.ImageField(blank=True, null=True, upload_to='studios/'),
        ),
    ]
