# Generated by Django 6.0.2 on 2026-02-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('genre', models.CharField(choices=[('ACTION', 'Action'), ('ADVENTURE', 'Adventure'), ('ANIMATION', 'Animation'), ('COMEDY', 'Comedy'), ('CRIME', 'Crime'), ('DRAMA', 'Drama'), ('FANTASY', 'Fantasy'), ('HORROR', 'Horror'), ('MYSTERY', 'Mystery'), ('ROMANCE', 'Romance'), ('SCI_FI', 'Science Fiction'), ('THRILLER', 'Thriller'), ('WAR', 'War'), ('WESTERN', 'Western'), ('DOCUMENTARY', 'Documentary'), ('OTHER', 'Other')], default='OTHER', max_length=15)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('budget', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Pre-Production', 'Pre-Production'), ('Filming', 'Filming'), ('Post-Production', 'Post-Production'), ('Released', 'Released'), ('Other', 'Other')], default='Other', max_length=15)),
                ('description', models.TextField(default='')),
                ('actors', models.ManyToManyField(blank=True, related_name='movies', to='people.actor')),
                ('directors', models.ManyToManyField(blank=True, related_name='movies', to='people.director')),
                ('writers', models.ManyToManyField(blank=True, related_name='movies', to='people.writer')),
            ],
        ),
    ]
