# Generated by Django 6.0.2 on 2026-02-21 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('studios', '0002_remove_studio_in_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='studios.studio'),
        ),
    ]
