# Generated by Django 6.0.2 on 2026-02-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_poster_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
