# Generated by Django 6.0.2 on 2026-02-21 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_movie_poster_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='studio',
        ),
    ]
