# Generated by Django 6.0.2 on 2026-02-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movie_studio'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_posted_file',
            field=models.URLField(default=''),
        ),
    ]
