# Generated by Django 6.0.2 on 2026-02-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movie_movie_posted_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_posted_file',
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_poster_file',
            field=models.URLField(default=''),
        ),
    ]
