# Generated by Django 6.0.2 on 2026-02-21 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_remove_movie_movie_posted_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_poster_file',
        ),
    ]
