# Generated by Django 6.0.2 on 2026-02-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_alter_movie_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_poster_image',
            field=models.ImageField(blank=True, null=True, upload_to='movies/'),
        ),
    ]
