# Generated by Django 6.0.2 on 2026-02-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_alter_movie_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('PRE-PRODUCTION', 'Pre-Production'), ('FILMING', 'Filming'), ('POST-PRODUCTION', 'Post-Production'), ('RELEASED', 'Released'), ('OTHER', 'Other')], default='Other', max_length=15),
        ),
    ]
