# Generated by Django 6.0.2 on 2026-02-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_alter_movie_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('Pre-Production', 'Pre-Production'), ('Filming', 'Filming'), ('Post-Production', 'Post-Production'), ('Released', 'Released'), ('Other', 'Other')], default='Other', max_length=15),
        ),
    ]
